### ISSUE TITLE
除了空调的其他码能放出来吗？

### ISSUE THREAD

**Issue by 1003657663** [Caffreyfans/IRbaby-android#10]
非常感谢作者的开发

**Comment by Caffreyfans** [comment]
是这样的，其他码码库里是有的。但是由于个人精力有限，也就只支持了空调码。其他码开发不难，我觉得难的是界面设计。

比如像电视，风扇之类的电器我不知道怎么去设计它的界面。而且由于 **Android** 与 **IOS** 不兼容的问题，导致我放弃继续维护 **Android** 客户端。下面的想法是开发内嵌 **Web** 服务器来作为 **UI**。

这个提案为自己也贴出来很久了，但是一直没行动。没办法啊，我看了下 **Web** 开发，我想用 **React** 框架去开发，但是这个自己还不熟悉，**C++** 也不熟悉。技术原因占大头，个人懒惰也占一头，这两个原因导致开发一直不能开始，抱歉了。但是我想说的是只要红外的市场还存在，`Next version` 就一定会出来。:fish:

**Comment by 1003657663** [comment]
我觉得有这种简单的实现方案
1. 比如先有一个这个：  电视/小米电视/xxxx  这种目录结构或者一个能够唯一识别这个红外码的字符串
2. 用户可以在安卓客户端点击对应的遥控，获取到这个遥控的所有码（一个json或者list）可以copy出来
2. 有了唯一的字符串，具体的功能，点击啥的都可以在homeassistant上由用户自己实现，可以使用第三方的ui库，也可以使用node-red
3. 用户点击homeassitant上的按钮或者node-red自己实现的mtqq按钮，触发mtqq发送唯一字符串，然后在8266上解析，然后发出红外。

这样的话界面问题就解决了，现在最大的问题就是其他平台的红外接入homeassistant困难，即使万能遥控器接入了，也只能通过学习来获得对应的一个码，无法批量学习所有的码，学习过程也比较不友好。

**Comment by Caffreyfans** [comment]
> 我觉得有这种简单的实现方案
> 
> 1. 比如先有一个这个：  电视/小米电视/xxxx  这种目录结构或者一个能够唯一识别这个红外码的字符串
> 2. 用户可以在安卓客户端点击对应的遥控，获取到这个遥控的所有码（一个json或者list）可以copy出来
> 3. 有了唯一的字符串，具体的功能，点击啥的都可以在homeassistant上由用户自己实现，可以使用第三方的ui库，也可以使用node-red
> 4. 用户点击homeassitant上的按钮或者node-red自己实现的mtqq按钮，触发mtqq发送唯一字符串，然后在8266上解析，然后发出红外。
> 
> 这样的话界面问题就解决了，现在最大的问题就是其他平台的红外接入homeassistant困难，即使万能遥控器接入了，也只能通过学习来获得对应的一个码，无法批量学习所有的码，学习过程也比较不友好。

你的意思是支持继续开发 Android 客户端吗？Android 客户端迟早会被抛弃的，单独开发一个客户端兼容不到其他平台的用户，这种情况我是持消极态度了。但是有其他开发者能够来维护现有的客户端我当然是支持的。但是由于自己代码太烂以及影响力不够维护者只有我本人，在这种情况下我就得考虑开发成本了。

**Comment by Caffreyfans** [comment]
从技术角度来说，是很容易实现的。就是开发者愿不愿意去做，红外码库都是现成的，只需要开发者调 API 就够了，根本没有什么技术难度。只有开发者是否对固件开发，客户端开发熟悉程度的区别，我也很无奈啊，自己两样都不在行，才导致是现在这么一个半成品的状态。我也在充电，但是充电效率不高，只是能对不起了只能慢慢等，或者用户换其他方案。
