### ISSUE TITLE
app无响应

### ISSUE THREAD

**Issue by bbzcx** [Caffreyfans/IRbaby-android#13]
手机：oppo
固件与app均为最新版本
问题：
1.选择空调后进入设备选择空白无响应
2.信号学习后，保存时为因为返回点击时，直接闪退

**Comment by Caffreyfans** [comment]
APP 存在 bug，需要把 MQTT 配置填写好才行。MQTT 服务器哪怕是没有，都是乱填一些数据，不能为空。

**Comment by bbzcx** [comment]
感谢，原来是我mqtt没设置密码，所以没填写导致的

> APP 存在 bug，需要把 MQTT 配置填写好才行。MQTT 服务器哪怕是没有，都是乱填一些数据，不能为空。

**Comment by Caffreyfans** [comment]
已修复
